package fvs.taxe;

public enum Button {
    TRAIN_DROP,
    TRAIN_PLACE,
    TRAIN_ROUTE,
    VIEW_ROUTE,
    GOAL_DROP,
    OBSTACLE_DROP,
    OBSTACLE_USE,
    TRAIN_CHANGE_ROUTE,
    SKIP_RESOURCE,
    SKIP_DROP,
    ENGINEER_DROP,
    ENGINEER_REPAIR_TRACK,
    ENGINEER_ADD_TRACK,
    ENGINEER_REMOVE_TRACK
}
